name: burke
favicon: null
layout_spectrum: 0.5549169613514096
typography_spectrum: 0.18148047453723848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2068087577354163
  lightness: 0.9502859564963728
  saturation: 0.3707206028047949
  rhythmicContrast: 0.29045658372342587
purpose: []
