name: burke
favicon: null
layout_spectrum: 0.5549169613514096
typography_spectrum: 0.18148047453723848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d4b7'
    - '#041a23'
    - '#807962'
    - '#9ea68a'
    - '#513d3d'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
