name: burke
favicon: null
layout_spectrum: 0.5549169613514096
typography_spectrum: 0.18148047453723848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf9f0'
    - '#3e3945'
    - '#bbb9c4'
    - '#6f6b7a'
    - '#98947f'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
